migration 작성
wecode-bootcamp-korea/38-2nd-GoodPlace-backend pull request #2
Opened 2022-11-01 09:26 UTC by haemong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- migration 작성

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- ERD에 따른 migration 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- ERD를 작성하고 데이터적 관점으로 생각하는 사고를 좀 더 넓혔습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2022-11-01 10:19 UTC, sangwoong03 requested changes
고생하셨습니다~!

놓치는 부분이 있을 수 있으니, 수정 반영 후 다시 한 번 더 확인하겠습니다~

2022-11-01 10:19 UTC, sangwoong03 commented on db/migrations/20221031120540_sellers.sql
> +    point DECIMAL(13, 3) NOT NULL,
결제 구현이 어렵기 때문에 point를 제공하고 삭감하는 방식으로 진행될 예정일텐데요.

데이터가 생성될 때 기본 값이 설정되어 있다면 key error를 방지할 수 있을 것 같네요!

2022-11-01 10:19 UTC, sangwoong03 commented on db/migrations/20221031120731_products.sql
> +    thumbnail VARCHAR(1000) NULL,
썸네일 사진임이 명확해보이지만 이미지 url를 담는 컬럼인 것을 확실하게 구분지어 주면 좋을 것 같습니다.
또한 해당 숙소 사진은 서비스 이용자가 참고해야하는 자료 중 하나이므로 NULL 값을 허용하면 안될 것 같네요.

```suggestion
    thumbnail_url VARCHAR(1000) NOT NULL,
```

2022-11-01 10:19 UTC, sangwoong03 commented on db/migrations/20221031120731_products.sql
> +    address VARCHAR(100) NULL,
해당 부분도 NULL 값을 허용하면 안될 것 같은데 혹시 다른 이유가 있으실까요?

2022-11-01 10:19 UTC, sangwoong03 commented on db/migrations/20221031120849_orders.sql
> +    check_out DATETIME NOT NULL,
네이밍을 명확하게 해주는 것이 좋아보입니다.
```suggestion
    check_in_date DATETIME NOT NULL,
    check_out_date DATETIME NOT NULL,
```

2022-11-01 10:19 UTC, sangwoong03 commented on db/migrations/20221031120840_order_histories.sql
> +DROP TABLE order_histories;
주문 내역을 관리하는 방법 중 하나로 history 테이블을 따로 생성할 수 있습니다.

하지만 아까 리뷰 시간에 같이 공유했던 내용처럼 orders 테이블로도 충분히 이력을 관리할 수 있을 것 같습니다!

2022-11-01 10:19 UTC, sangwoong03 commented on db/migrations/20221031120753_users.sql
> +    point DECIMAL(13,3) NOT NULL,
포인트 기본값 설정을 해주어야 따로 key error가 발생하지 않을 것 같습니다~!

2022-11-02 02:28 UTC, sangwoong03 requested changes

2022-11-02 02:28 UTC, sangwoong03 commented on db/migrations/20221031120819_options.sql
> +)
rooms에 대한 options가 여러가지인 경우면 room : option = 1 : N 관계로 보여집니다.

```suggestion
CREATE TABLE options {
    id int NOT NULL AUTO_INCREMENT PRIAMARY_KEY,
    name VARCHAR(16) NOT NULL,
    room_id INT
    CONSTRAINT options_room_id_fkey FOREIGN KEY (room_id) REFERENCES (rooms_id)
}

```

2022-11-02 02:28 UTC, sangwoong03 commented on db/migrations/20221031120753_users.sql
> +    social_id VARCHAR(3000) NOT NULL,
소셜로그인의 경우 반환되는 소셜 아이디의 필드를 공식문서에서 확인 후 다시 설정해주세요!

[카카오 developers](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info)에서 확인할 수 있습니다.

2022-11-02 02:28 UTC, sangwoong03 commented on db/migrations/20221031120540_sellers.sql
> +)
소셜로그인의 경우 반환되는 소셜 아이디의 데이터타입을 공식문서에서 확인 후 다시 설정해주세요!

[카카오 developers](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info)에서 확인할 수 있습니다.

2022-11-02 02:28 UTC, sangwoong03 commented on db/migrations/20221031120942_product_details.sql
> +-- migrate:down
해당 테이블은 어떤 테이블인가요!?
불필요하다면 삭제해주세요!

2022-11-02 02:28 UTC, sangwoong03 commented on db/migrations/20221031120531_order_statuses.sql
> +    status_description VARCHAR(100) NOT NULL
주문 상태의 설명에 대한 컬럼이라면 `description`만 작성해주는 것이 명확할 것 같습니다!

단일 주문 상태만 가리킨다면 `name`으로 컬럼명을 간략하게 변경해보는 것은 어떨까요??

2022-11-02 02:28 UTC, sangwoong03 commented on db/migrations/20221031120849_orders.sql
> +    order_status_id INT NOT NULL,
최초 예약 시 예약 대기 혹은 결제 대기 상태를 기본값으로 갖고 있으면 좋을 것 같습니다!
```suggestion
    order_status_id INT NOT NULL DEFAULT 1,
```

2022-11-02 02:28 UTC, sangwoong03 commented on db/migrations/20221031120903_reviews.sql
> +    score INT NOT NULL,
각각의 별점 1, 2, 3, 4, 5를 score로 보고 이 스코어를 주었을 때의 데이터 관리는 `rating`이라는 컬럼으로 관리하면 좋을 것 같습니다!

```suggestion
    rating INT NOT NULL,
```

2022-11-02 03:50 UTC, haemong commented on db/migrations/20221031120942_product_details.sql
> +-- migrate:down
삭제하였습니다!

2022-11-02 03:52 UTC, haemong commented on db/migrations/20221031120819_options.sql
> +)
N : N 관계인 거 같아서 중간테이블을 새로 만들었습니다.

2022-11-02 04:32 UTC, sangwoong03 requested changes

2022-11-02 04:32 UTC, sangwoong03 commented on db/migrations/20221031120540_sellers.sql
> +    social_id INT NOT NULL,
카카오 공식문서에 의하면 카카오가 반환하는 아이디의 데이터 타입은 `long` 타입이라고 명시되어 있습니다!

`long` 타입의 유호 범위는 1~9223372036854775807까지의 숫자이기 때문에 `MySQL`에서 해당 유효 범위를 포괄할 수 있는 데이터 필드를 설정해주세요!

2022-11-02 06:45 UTC, sangwoong03 approved these changes
LGTM 👍

2022-11-02 06:45 UTC, merged