[ADD] user endpoint 기능 구현
wecode-bootcamp-korea/38-2nd-GoodPlace-backend pull request #4
Opened 2022-11-02 17:28 UTC by dnrdls7

1. 카카오톡 로그인 기능 구현
2. 회원이 아니라면, kakao로부터 받은 kakaoId를 응답
3. kakaoId를 포함한 필수 입력 사항으로 signup 요청 받고, 회원가입 진행

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- kakao api를 활용한 로그인 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 기능
 - user가 kakao 로그인을 요청하고, 동의항목에 동의하면, kakao가 설정해둔 Redirect URI로 
    qurey parameter로 인가코드가 포함되어 응답을 보냄
 - 응답받은 인가코드로 kakao로부터 access token을 발급을 요청
 - 발급 받은 token을 가지고 유저의 정보를 요청
 - 응답받은 유저의 정보를 가지고 DB에서 해당 유저의 정보를 확인하고, 토큰을 발급

2. 회원가입 기능
 - 응답받은 유저의 정보를 가지고 DB를 조회한 결과, 회원이 아닐 경우
 - kakaoId를 응답함 (다음 회원가입 필수 정보와 함께 돌려받기 위함)
 - user가 회원가입 필수 정보를 작성하고 응답한 kakaoId와 함께 정보를 요청 받음
 - 요청에 담긴 필수 정보와 kakaoId를 가지고 회원가입을 진행

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 처음으로 외부 api를 사용하는 경험을 하면서, 외부 공식문서을 참고하게되었고, 해당 과정에서 많은 것을 배우게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-11-03 03:11 UTC, sangwoong03 requested changes
signIn부터 수정해주세요!

2022-11-03 03:11 UTC, sangwoong03 commented on routes/userRouter.js
> +router.post('/kakao/signup', userController.signUp);
현재는 카카오를 통한 로그인을 구현하도록 기획이 되어 있어 엔드포인트 작성 시 다음과 같이 작성해주신 것으로 보입니다.

다만 서비스를 운영하면서 일반 회원가입, 다른 플랫폼의 로그인 API를 연동하는 경우가 있을 수 있으므로 엔드포인트를 다음과 같이 수정하는 것이 좋을 것 같습니다!
```suggestion
router.get('/signin', userController.signIn);
router.post('/signup', userController.signUp);
```

2022-11-03 03:11 UTC, sangwoong03 commented on controllers/userController.js
> +  }
`query parameter`로 받는 데이터에 대한 키에러를 처리할 이유가 따로 있는 것인가요?

2022-11-03 03:11 UTC, sangwoong03 commented on services/userService.js
> +      redirect_uri: "http://127.0.0.1:3000/user/kakao/signin",
redirect uri는 환경변수로 관리해 주세요.

2022-11-03 03:11 UTC, sangwoong03 commented on services/userService.js
> +  const getKakaoUserInfo = {
위에서 인가코드를 받아올 때의 변수명을 고려하여 네이밍을 해주면 좋을 것 같습니다!

```suggestion
  const getKakaoUserOption = {
```

2022-11-03 03:11 UTC, sangwoong03 commented on services/userService.js
> +  console.log(KakaoUserProfile);
불필요한 코드는 push 이전에 확인 후 삭제해주세요

2022-11-03 03:11 UTC, sangwoong03 commented on services/userService.js
> +        "Authorization" : `Bearer ${getKakaoToken["access_token"]}`
변수를 새로 할당한다면 더 깔끔한 코드를 작성할 수 있을 것 같네요! 
```suggestion
    const KAKAO_TOKEN = getKakaoToken["access_token"]
   ....
        "Authorization" : `Bearer ${KAKAO_TOKEN}`
```

2022-11-03 03:11 UTC, sangwoong03 commented on services/userService.js
> +  }
해당 코드 실행되나요?

2022-11-03 16:46 UTC, dnrdls7 commented on controllers/userController.js
> +  }
code의 값이 없다면 이후 service단 함수의 실행이 의미가 없게되어 키에러로 설정하였습니다.
현재 코드는 사실상 카카오의 code로만 로그인을 할 수 있는 endpoint이므로 위의 endpoint도 /kakao/signin & signup으로 하였습니다.

2022-11-04 00:08 UTC, sangwoong03 requested changes
로그인과 회원가입 로직이 하나의 함수에서 진행된다면 service 단의 코드를 더욱 간결하게 작성할 수 있을 것 같습니다.
리뷰 확인 후 이해가 가지 않는 부분에 대해서 반드시 질문해주세요!!

2022-11-04 00:08 UTC, sangwoong03 commented on models/userDao.js
> +}
createSeller 함수가 반환하는 값이 없어보이네요

push 하기 전 로컬 환경에서 코드가 정상적으로 작동하는지 소프트웨어 세션 시간에 접한 방법들을 적용하여 확인하는 습관을 길러주세요~!

2022-11-04 00:08 UTC, sangwoong03 commented on controllers/userController.js
> +});
만약 카카오 아이디 정보를 요구하는 회원가입 로직을 따로 작성하게 된다면 클라이언트에서 사용자의 카카오 아이디를 다시 인증하는 절차가 필요할 것 같습니다.

카카오 로그인 인증을 통해 인가코드와 액세스토큰을 통해 사용자 정보를 받아오는데요.

Dao에서 getUserBySocialId 함수를 통해 하나의 로직에서 로그인과 회원가입을 진행할 수 있을 것 같습니다.

<카카오 로그인>
1. 인가코드 및 액세스 토큰 발급
2. 사용자 정보 가져오기
3. 사용자 정보가 없다면 ( `getuserBySocialId` 함수로 반환되는 값이 없다면, creatUser 함수를 통해 바로 회원가입 진행)
4. 사용자 정보가 있다면 ( `getuserBySocialId` 함수로 반환되는 값이 있다면, 바로 로그인 진행)

2022-11-04 04:07 UTC, dnrdls7 commented on models/userDao.js
> +}
seller 회원가입의 경우 user로도 가입이 되기 때문에 createuser는 생성된 userId를 반환하여, 이후 seller로 가입한 경우 seller의 userId값이 들어갑니다. 하지만 seller는 data만 저장되면 이후 연관되는 로직이 없어서 return을 설정하지 않았습니다.

2022-11-04 04:16 UTC, dnrdls7 commented on controllers/userController.js
> +});
적어주신 flow에서 3번에서 4번 내용이 이해가 잘 안되는거 같습니다.
3번의 경우 현재 인가코드로 카카오 엑세스 토큰을 가져와 토큰으로 사용자 정보를 제공받아 해당 정보를 가지고 
서버 db에서 해당 유저가 회원인지를 판단하여, 회원일 경우 jwt토큰을 발급합니다.

하지만 회원가입의 경우 필수로 포함되어야 하는 정보(nickName, phoneNumber)가 추가적으로 있어서, 회원가입으로 바로 
연결할 수 없을 것으로 저는 생각됩니다.

만일 회원가입까지 연결하려면 애초 로그인 과정에서 필수 추가 정보인 nickName과 phoneNumber가 항상 포함되어야 있어야할 것 같은데, 혹시 다른 내용일지 제가 리뷰 내용을 이해를 잘 못하는거 같습니다.

2022-11-04 05:21 UTC, sangwoong03 requested changes

2022-11-04 05:21 UTC, sangwoong03 commented on services/userService.js
> +  const redirectUri = process.env.REDIRECT_URI;
변수 네이밍 컨벤션을 따라주세요!
```suggestion
  const API_KEY = process.env.API_KEY;
  const REDIRECT_URI = process.env.REDIRECT_URI;
```

2022-11-04 05:21 UTC, sangwoong03 commented on services/userService.js
> +  }
이중 조건문의 조건을 하나로 합쳐 가독성을 높일 수 있을 것 같습니다!
```suggestion
  const KAKAO_EMAIL = kakaoUserInfo.kakao_account.email
  if ( !user && !KAKAO_EMAIL) {
    const data = {
      id : kakaoUserInfo.id,
      email : KAKAO_EMAIL
    }

    return data;
  }
```

2022-11-04 05:21 UTC, sangwoong03 commented on services/userService.js
> +  const checkUserBySocialId = await userDao.getUserBySocialId( kakaoUserInfo.id );
반환되는 값은 user 정보를 담은 객체이므로 변수명을 `user`로 네이밍하는 것이 가독성에 좋을 것 같습니다.
```suggestion
  const user = await userDao.getUserBySocialId( kakaoUserInfo.id );
```

2022-11-07 01:05 UTC, sangwoong03 requested changes

2022-11-07 01:05 UTC, sangwoong03 commented on services/userService.js
> +  signUp
해당 부분 들여쓰기만 수정해주세요! 나머지는 좋아보입니다 👍

2022-11-07 01:24 UTC, dnrdls7 commented on services/userService.js
> +  signUp
수정해서 올리겠습니다!

2022-11-07 07:14 UTC, sangwoong03 approved these changes
LGTM 👍

2022-11-07 07:14 UTC, merged