[ADD] product list 기능 구현
wecode-bootcamp-korea/38-2nd-GoodPlace-backend pull request #5
Opened 2022-11-03 02:05 UTC by dnrdls7

1. user 현재 좌표를 받아, 설정한 반경 내의 product list return

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- user 일정 거리 내에 있는 product list 필터 기능

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. user 일정 거리 내에 있는 product list 필터 기능
- user의 현재 좌표와 거리를 입력 받아, user 반경 (입력 거리) 내에 있는 product list를 제공한다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 현재 사용되는 map api의 동작 원리에 대하여 공식문서를 통하여 조금이나마 알게 되었습니다. 
- 위도 경도를 사용하여 거리를 계산하는 방법에 대하여 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-11-03 06:24 UTC, sangwoong03 requested changes

2022-11-03 06:24 UTC, sangwoong03 commented on services/productService.js
> +  }
데이터 타입을 확인하기 위한 로직 작성에 대한 의도는 정말 좋습니다!

다만 `isNaN()`에 따옴표로 감싸진 숫자을 넣었을 때 어떤 결과가 나오는 지 확인해보시고 좀 더 알맞은 코드를 구현해주세요.

참고 [링크](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN)를 확인해주세요.

2022-11-03 06:24 UTC, sangwoong03 commented on controllers/productController.js
> +  const productByUserCoordinate = productService.getProductDistanceByUser( latitude, longitude, distanceMeter );
함수의 인자의 데이터 타입을 바꾸는 과정은 controller에서 진행 후 service에서 호출할 수 있도록 수정해주면 좋을 것 같습니다!

2022-11-03 06:24 UTC, sangwoong03 commented on models/enum.js
> +});
1. 우선 ENUM 타입에 대한 정의 정리가 필요할 것 같습니다.
`Enumerated type`의 줄임말로써 열거형 타입이나 데이터 집합을 가리킵니다.
enum이라는 파일명에서 관리하는 모듈과는 거리가 있어보여 수정이 필요할 것 같습니다.

따라서 지금 작성하신 코드는 ENUM으로 관리하기 보다는 해당 쿼리를 반환하는 하나의 모듈로 작성해주는 것이 좋아보입니다!

아래는 예시이니 참고해주세요!

```suggestion
function distanceFormulaForQuery(latitude, longitude) {
  const FORMULA_QUERY = `(6371 * acos( cos( radians( ${latitude} ) ) * cos( radians( latitude ) ) * cos( radians( longitude ) - radians( ${longitude} ) ) + sin( radians( ${latitude} ) ) * sin( radians( latitude ) ) ) ) AS distance`
  return FORMULA_QUERY
})
```

2. 유저의 위치 기반에 따른 거리 차이도 해당 코드로 구현할 수 있는 것인가요?

2022-11-03 06:24 UTC, sangwoong03 commented on models/productDao.js
> +}
formula 쿼리 객체를 수정하면서 다소 수정할 부분이 몇군데 보입니다.

enum이 아닌 쿼리 자체를 반환하는 모듈로서 수정 후 해당 코드도 수정해주세요!

추가로, query문 포맷팅 수정도 해주면 좋을 것 같습니다!
```suggestion
// example
const { distanceFormulaForQuery } = require('./fomualQuery');

const getProductDistanceByUser = async ( latitude, longitude, distance ) => {
  return await database.query(`
    SELECT count(*)
    FROM (
      SELECT ${distanceFormulaForQuery(latitude, longitude)}
      FROM products
    ) AS data
    WHERE data.distance <= ?;`,
    [ distance ]
  );
}
```

2022-11-03 06:24 UTC, sangwoong03 commented on routes/productRouter.js
> +router.get('/distance', productController.productDistanceByUser);
다른 코드 로직을 보았을 때 리스트 페이지에서 상품 `전체리스트`가 반환되고,
그 리스트 중에서 유저의 위치를 기반으로 특정 거리에 있는 상품들을 `필터링` 하는 것으로 보입니다.

`/distance` path로 들어가야만 특정 상세 리스트를 받을 수 있는 것인가요~?

RESTful API 기반의 API를 구현하기 위해 endpoint를 명확하게 작성해주면 좋을 것 같습니다.

2022-11-06 01:42 UTC, dnrdls7 commented
1. productFunction 파일을 따로 생성하여 작성하였는데, 해당 방법이 옳은 방법인지 잘 모르겠습니다.
2. 엔드포인트 관련 = 말씀해주신 것 처럼 상품리스트가 나오고, 거리에 따른 정렬은 필터링 옵션으로 동작합니다.
하지만 홈페이지에서는 내주변이라는 탭으로 들어가지 않으면 상품 리스트에 거리도 표기되지않아 다른 페이지라고 판단했습니다.
'내주변'이라는 탭으로 들어왔다라는 엔드포인트로 product/distance를 만들었고, 이 후 필터링과 소팅이 가능하도록 하였는데,
정확한 이해가 아직 부족한 것 같습니다.

2022-11-07 12:55 UTC, sangwoong03 requested changes

2022-11-07 12:55 UTC, sangwoong03 commented on models/enum.js
> +});
enum 타입을 통해 반환되는 값이 실제 데이터베이스 상에서 4와 12라는 값인가요?

2022-11-07 12:55 UTC, sangwoong03 commented on controllers/productController.js
> +    const productByUserCoordinate = await productService.getProductDistanceByUser( +latitude, +longitude, +distanceMeter, JSON.parse(optionArray), premiumOption, sortBy, +limit, +offset );
`JSON.parse()` 메서드를 통해 받아오는 optionArray라는 인자에는 어떤 값이 담겨져 들어오나요!?

2022-11-07 12:55 UTC, sangwoong03 commented on controllers/productController.js
> +  //sortBy 거리순
불필요한 주석 삭제해주세요!

2022-11-07 12:55 UTC, sangwoong03 commented on controllers/productController.js
> +  const { latitude, longitude, distanceMeter, optionArray, limit, offset } = req.query;
`내 주변`의 숙소를 찾기 위해 필수적으로 필요한 인자들을 request의 body로 받고,
나머지 필터링을 위한 부수 정보들은 query로 받으면 어떨까요?

2022-11-08 05:43 UTC, dnrdls7 commented on models/productDao.js
> +  ${sortByPremiumForQuery( premiumOption, sortByOptionForQuery( sortBy ) )}`
첫번째 SELECT ~ 두번째 SLECT, FROM 은 오직 distance 로 where를 걸기 위해 생겨난 코드입니다.
해당 부분이 없어도 데이터는 원하는 형태로 나오지만 distance로 검색이 되지않는데, 더 좋은 해결방법이 없는지 궁금합니다.
'distance'로는 검색되지만 조건이 제대로 동작하지 않았습니다.

1. distance 를 항목을 객체에 담아 response 했을 때, 컬럼명인 distance 도 string, value인 값들도 모두 string 이였습니다.
2. TYPE 변환 SQL CONVERT 함수를 사용 해봤을 때, 문법 오류가 발생했습니다. => 테이블의 기존 컬럼이 아닌, 가상으로 만들어 냈기 때문이라고 생각합니다.

2022-11-08 05:43 UTC, dnrdls7 commented on models/functionForProduct.js
> +}
product(숙소)에 포함된 room(숙소에 포함된 방)들이 가진 옵션을 하나의 컬럼에 배열로 표기할 목적으로
처음에는 JSON_ARRAYAGG를 사용했지만, 방들의 옵션이 방1 = [1], 방2 = [1,2], 방3 = [1,2,3] 일 경우
[1, 1, 2, 1, 2, 3] 처럼 중복되어 모든 방의 옵션들이 나열되는 방식으로 구현되었습니다.
그래서 JSON_OBJECT를 JSON_KEY로 감싸는 방식으로 중복 제거를 구현하였습니다.
하지만 위의 예시를 결과로 본다면 ,table plus 에서의 실행 결과는 정상적으로 `["1", "2", "3"]` 나오지만
postman의 응답 결과는 `[\"1\", \"2\", \"3\"]` 처럼 나오는데, 어떤 원인인지 파악하지 못하였습니다.
controller 단에서 response 되는 값을 console.log 했을 때는 `["1", "2", "3"]` 형태로 나오는 걸 확인했습니다.

2022-11-08 05:43 UTC, dnrdls7 commented on controllers/productController.js
> +    const productByUserCoordinate = await productService.getProductDistanceByUser( +latitude, +longitude, +distanceMeter, JSON.parse(optionArray), premiumOption, sortBy, +limit, +offset );
유저가 원하는 룸의 옵션들이 배열에 담겨서 optionArray라는 변수로 들어옵니다.
유저가 (티비, 냉장고, 스타일러) 처럼 룸에 포함되어야하는 옵션들로 필터링을 하기 위한 인자들 배열로 받아옵니다.

2022-11-08 05:43 UTC, dnrdls7 commented on controllers/productController.js
> +  //sortBy 거리순
삭제하겠습니다.

2022-11-08 05:43 UTC, dnrdls7 commented on controllers/productController.js
> +  const { latitude, longitude, distanceMeter, optionArray, limit, offset } = req.query;
http method가 기능상 get이라고 생각해서, get으로 설정하였는데, body 기능을 쓰려면 http method를 다시 생각해봐야할까요?

2022-11-08 05:43 UTC, dnrdls7 commented on models/enum.js
> +});
설계상 대실 비용, 숙박 비용을 따로 데이터로 가지고있지 않습니다.
시간당 비용을 데이터로 가지고 있고, 숙박의 체크인~체크아웃은 정해져있고, 대실의 최소 시간은 4시간으로 설정하였습니다.
유저에게 보여지는 가격 정보는 대실의 최소 비용과 숙박 비용이라서 비용에 최소값이 나타날 수 있는 배수(상수값)을 저장하였습니다.

2022-11-09 02:28 UTC, sangwoong03 requested changes

2022-11-09 02:28 UTC, sangwoong03 commented on controllers/productController.js
> +  let sortBy = req.query.sortBy;
어제 말씀드린 부분입니다!
요청의 query parameter에서 받아오는 값들을 다음과 같이 작성해주면 if 조건문을 사용하지 않아되 되기 때문에 좀 더 간결해질 것 같네요!

해당 부분 수정해주세요~!

```suggestion
  let sortBy = req.query.sortBy ? req.query.sortBy : "default";
```

2022-11-09 02:44 UTC, dnrdls7 commented on controllers/productController.js
> +  let sortBy = req.query.sortBy;
네 수정하겠습니다

2022-11-09 09:05 UTC, sangwoong03 requested changes

2022-11-09 09:05 UTC, sangwoong03 commented on services/productService.js
> +};
마이너한 수정 사항: 들여쓰기 수정 부탁드려요~!

2022-11-10 00:12 UTC, sangwoong03 approved these changes
고생하셨습니다 👍

2022-11-10 00:12 UTC, merged