구매하기 api 구현 완료
wecode-bootcamp-korea/38-2nd-GoodPlace-backend pull request #7
Opened 2022-11-03 18:47 UTC by iflov

order 관련 api 구현 완료 하였습니다

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
주문하기 CRD
DELETE 날짜별로 환불 다르게 적용
상세 예약 조회 
전체 예약조회

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
예약하기 테이블에 데이터 추가 및 users 에 point 차감
예약 환불 시 users point 환불 및 orders 상태 코드 변경
특정 예약 정보 조회 
특정 유저의 예약 정보 조회

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
제일 중요한건 멘탈과 생각이 제일 중요하다고 깨달았습니다.

<br />

## :: 기타 질문 및 특이 사항
사랑합니다 부족한점 친절하게 설명 부탁드려도 될까요~ 제맘 알죠?

2022-11-04 01:18 UTC, sangwoong03 requested changes
dao 쿼리문 전반적인 포매팅 및 들여쓰기 수정해주세요!

service 로직은 대면으로 리뷰 드릴게요

s3 관련 코드는 분리해서 다른 pr로 올려주세요!

2022-11-04 01:18 UTC, sangwoong03 commented on routes/index.js
> +
뷸필요한 공백 삭제해주세요.

구매하기 API에 s3 업로드 코드가 필요한 코드인지 확인해보시고, PR을 분리해주세요.
```suggestion
const orderRouter = require('./orderRouter');

```

2022-11-04 01:18 UTC, sangwoong03 commented on routes/orderRouter.js
> +router.get('/searchAll', orderController.getAllOrderByUserId);
RESTful API 기반의 API를 구현하기 위해 엔드포인트 uri에 동사 대신 명사를 사용합니다.

엔드포인트에 해당 하는 api 기능들을 고려하여 수정해주세요.

특정 id 값을 통해 정보를 찾는 경우 `path parameter`를 사용할 수 있습니다.

2022-11-04 01:18 UTC, sangwoong03 commented on controllers/orderController.js
> +})
작업한 코드를 push하기 전 로컬 환경에서 테스트를 진행해보셨나요?

현재 `userId`를 주석처리 한 상태로 `userId`를 인자로 DAO단 코드까지 보내주고 있습니다.

올바른 코드인지 다시 한 번 확인해주세요.

2022-11-04 01:18 UTC, sangwoong03 commented on controllers/orderController.js
> +  const { userId } = req.body;
유저의 정보를 body로 받는 것이 좋은지 프론트엔드 개발자와 협의 후 더욱 안전한 방법으로 수정해주세요.

2022-11-04 01:18 UTC, sangwoong03 commented on controllers/orderController.js
> +  const { orderId , userId, roomId } = req.query;
유저의 정보를 query로 받는 방법에 대해 프론트엔드 개발자와 협의 후 더욱 안전한 방법으로 수정해주세요.

2022-11-04 01:18 UTC, sangwoong03 commented on controllers/orderController.js
> +})
함수명에 의하면 `userId`에 해당하는 정보를 요청으로부터 받거나
혹은 요청을 통해 받은 정보로 userId를 찾아 주문 정보를 찾는 로직을 처리할 것으로 예상이 됩니다.

함수명을 수정하거나, 함수명에 받도록 로직을 다시 한번 생각해주세요!

2022-11-04 01:18 UTC, sangwoong03 commented on services/orderService.js
> +  const getRoomPriceByRoomId = await orderDao.getRoomPriceByRoomId( +roomId );
`roomId`의 데이터 타입은 controller에서 변경 후 service에서 호출해주세요!

2022-11-04 01:18 UTC, sangwoong03 commented on services/orderService.js
> +  const getUserPointByUserId = await orderDao.getUserPointByUserId( +userId );
`userId`의 데이터 타입은 controller에서 변경 후 service에서 호출해주세요!

2022-11-04 01:18 UTC, sangwoong03 commented on services/orderService.js
> +
불필요한 공백은 삭제해주세요

2022-11-04 01:18 UTC, sangwoong03 commented on services/orderService.js
> +}
현태님 함수 내부에서 작동하는 조건문이기 떄문에 들여쓰기 신경써주세요.

첫번째 조건문은 특정 값이 0인 경우로서 아래와 같이 작성함으로써 가독성을 높일 수 있습니다.

```suggestion
  if(  !getUserPointByUserId ){
    const err = new Error('USER_POINT_IS_EMPTY');
    err.statusCode = 400;
    throw err;
  }

  if( pointChange < 0){
    const err = new Error('PLEASE_ADD_YOUR_POINT');
    err.statusCode = 400;
    throw err;
  }

  if( pointChange > 0 ) {
  const orderData = await orderDao.createOrder( +userId , +roomId, checkIn, checkOut , pointChange, orderStatusEnums.RESERVATE_ON_ORDER_STATUS_ID ); 
  
  return orderData;
}
```

2022-11-04 01:18 UTC, sangwoong03 commented on services/orderService.js
> +}
현태님. 코드 가독성을 위해 들여쓰기를 수정해주세요.

이따 라운지 시간에 해당 코드 같이 리팩토링 합시다.

2022-11-04 01:18 UTC, sangwoong03 commented on models/orderDao.js
> +  }
해당 함수 반환하는 데이터가 없는 것 같은데 service 단에서 이 함수 실행 결과가 반환이 되나요?

2022-11-04 01:18 UTC, sangwoong03 commented on models/orderDao.js
> +  `)
formatting 수정해주세요~!
```suggestion
  const allOrderByUserId =  await database.query(`
    SELECT
      rooms.thumbnail_url AS thumbnail,
      products.name AS productName,
      rooms.name AS roomName,
      order_statuses.description AS description,
      orders.id AS orderId,
      orders.check_in_date AS checkIn,
      orders.check_out_date AS checkOut
    FROM orders
    JOIN order_statuses ON orders.order_status_id = order_statuses.id
    JOIN rooms ON orders.room_id = rooms.id
    JOIN products ON products.id = rooms.product_id
    WHERE rooms.id = ${roomId}
      AND products.id = ${productId}
      AND order_statuses.id = ${orderStatus}
  `)
```

2022-11-07 07:44 UTC, sangwoong03 requested changes

2022-11-07 07:44 UTC, sangwoong03 commented on routes/orderRouter.js
> +router.get('/searching', loginRequired, orderController.getOrderByOrderId);
RESTful한 엔드포인트를 위해 `orderId`를 path parameter로 받아오는 것으로 수정하면 좋을 것 같네요!
```suggestion
router.get('/:orderId', loginRequired, orderController.getOrderByOrderId);
```

2022-11-07 07:44 UTC, sangwoong03 commented on routes/orderRouter.js
> +router.get('/searchingAll', loginRequired, orderController.getAllOrderByUserId);
이미 router 모듈에서 `/order`의 path가 설정되어 있기 때문에 해당 엔드포인트를 명시하지 않아도 될 것 같습니다!
```suggestion
router.get('/', loginRequired, orderController.getAllOrderByUserId);
```

2022-11-07 07:44 UTC, sangwoong03 commented on utils/auth.js
> +  // 1) Getting token and check if it is there
코드에 대한 설명을 주석으로 전달하려는 의도는 좋습니다!

다만 코드를 수정하였을 때 주석까지 수정해야되는 부수 업무가 생길 뿐더러 코드 수정 이후 주석을 수정하지 않았다면 다른 협업 개발자나 오픈 소스를 이용하는 사용자들에게 혼동을 줄 수 있습니다!

코드의 길이가 길지 않고 코드 자체만으로도 가독성을 좋게 작성할 수 있는 부분이니 `auth` 모듈의 주석은 삭제해도 좋을 것 같네요!

2022-11-07 07:44 UTC, sangwoong03 commented on utils/auth.js
> +  req.user = user;
DAO에서 호출 된 user를 반환하지 말고 토큰 자체에서 반환하고 있는 payload 정보에서 유저 정보를 반환해주세요!
```suggestion
  req.user = decoded;
  // 혹은
  req.user = docoded.id // payload에 담은 유저의 정보 활용
```

2022-11-07 07:44 UTC, sangwoong03 commented on controllers/orderController.js
> +  const  userId  = req.user[0].userId;
`auth middleware`를 통해 반환되는 `req.user`는 현재 userDao에서 반환되는 값으로 되어 있습니다.

토큰 자체를 복호화 했을 때 반환되는, 즉 payload에 담겨있는 유저의 정보를 사용한다면 해당 코드는 다음과 같이 바꿀 수 있습니다.

controller의 동일 부분 수정해주세요~!

 ```suggestion
 // req.user = decoded일 경우
  const  userId  = req.user.userId;
  
  // req.user = decoded.userId일 경우
  const userId = req.user
```

2022-11-07 07:44 UTC, sangwoong03 commented on controllers/orderController.js
> +  const { roomId, checkIn, checkOut } = req.body;
요청으로 받는 JSON 형태의 body 값들에 대해 `key error`와 같은 예외처리도 고려해주어야 할 것 같습니다~!

2022-11-07 07:44 UTC, sangwoong03 commented on models/orderDao.js
> +    console.log(typeof checkIn)
불필요한 코드는 삭제해주세요~!

2022-11-07 07:44 UTC, sangwoong03 commented on models/orderDao.js
> +    console.log(data)
불필요한 코드는 삭제해주세요~!

2022-11-08 15:15 UTC, sangwoong03 requested changes
고생하셨습니다. 다만 `push 하기 전에 코드를 꼼꼼하게 다시 확인하는 습관`을 길러주세요.

코드를 `github에 공유하고 배포하는 행위`에 대해 다시 한번 생각해주세요.

orderSerivce에서 로그를 확인하는 코드가 일부 식별되는데 해당 서비스를 이용하는 사용자들에게 반드시 필요한 기능이 아닙니다. 

data 타입에 대해 신경을 많이 쓰시는 부분에 대해서는 정말 좋은 것 같습니다.

다만, 앞서 리뷰드렸듯 controller에서 요청을 통해 받은 데이터에 대한 타입을 재정의한다면, service나 model에서 다시 수정하거나, 데이터 타입이 달라 발생하는 문제점을 사전에 차단할 수 있을 것 같습니다.

리뷰 꼼꼼하게 읽어보시고, 이해가 되지 않는 부분은 댓글이나 DM으로 말씀부탁드립니다.

2022-11-08 15:15 UTC, sangwoong03 commented on models/enums.js
> +})
주문(예약) 상태에 대한 데이터를 객체 혹은 enum을 통해 매핑하는 경우 다음과 같이 작성해준다면 차후 사용 시 확장성이 높을 것 같습니다.
```suggestion
const orderStatusEnums = Object.freeze({
  RESERVED: 1,
  CANCELED: 2,
  COMPLETED: 3
})
```

2022-11-08 15:15 UTC, sangwoong03 commented on controllers/orderController.js
> +  const { roomId, checkIn, checkOut } = req.body;
12번 코드 라인을 통해 request의 body에서 3개 정보를 구조분해할당을 통해 값을 받아오고 있습니다.

이에 따른 예외처리를 진행해주세요!

에러메시지는 좀 더 명확하게 작성해주세요!
```suggestion
  const { roomId, checkIn, checkOut } = req.body;
  
  if( !roomId || !checkIn || !checkOut){
    const error = new Error('KEY_ERROR');
    error.statusCode = 400;
    throw error;
  }

```

2022-11-08 15:15 UTC, sangwoong03 commented on controllers/orderController.js
> +  // const { userId } = req.query;
사용하지 않는 코드는 push하기 전에 삭제해주세요~!

2022-11-08 15:15 UTC, sangwoong03 commented on models/orderDao.js
> +    `)
위의 쿼리와 동일하게 배열에 parameter를 담아 매핑하는 코드로 수정해주세요!

다른 쿼리문도 확인 후 수정해주세요~

```suggestion
    await queryRunner.query(`
      UPDATE users
        SET point= ?
      WHERE id= ?
    `, [pointChange, userId])
```

2022-11-09 02:46 UTC, iflov commented on controllers/orderController.js
> +  // const { userId } = req.query;
userId 부분 frontend분께서 아직 토큰을 못하여서 ㅠㅠ 혹시 프론트분 해결 될때까지 남겨두어도 될지 문의드립니다

2022-11-09 03:02 UTC, sangwoong03 commented on controllers/orderController.js
> +  // const { userId } = req.query;
이런 문제를 해결하기 위해 unit test 단계를 통해 사전 검증을 할 수 있습니다!

말씀대로 로컬 테스트가 충분히 진행되지 않았다고 판단됩니다.

해당 PR은 추가 기능 구현 라벨로 변경 후 모든 테스트가 완벽히 수행되면 다시 리뷰 진행하겠습니다.

2022-11-10 00:16 UTC, sangwoong03 requested changes
컨플릭트 해결해주세요.

어제 말씀드린 부분 반영이 잘 안되었네요.

2022-11-10 00:16 UTC, sangwoong03 commented on controllers/orderController.js
> +  const { userId } = req.query;
현태님 토큰 복호화를 통해 유저 정보를 받아오는 코드만 남기고 쿼리로 유저 정보 받아오는 코드 지워주세요.

2022-11-10 02:44 UTC, iflov commented on controllers/orderController.js
> +  const { userId } = req.query;
죄송합니다 어제 말씀해주신 부분 및 conflict 해결 완료하였습니다!

2022-11-10 05:21 UTC, sangwoong03 approved these changes
고생하셨습니다 👍

2022-11-10 05:22 UTC, merged