[ADD] product main/list 기능 구현
wecode-bootcamp-korea/38-2nd-GoodPlace-backend pull request #8
Opened 2022-11-04 13:42 UTC by haemong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지 sorting/filtering 기능 구현
- 상세페이지 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인페이지 sorting 기능 구현
- GET 요청에 의한 메인페이지의 정보를 쿼리문으로 알맞게 만들고 sorting 기능을 추가하여 구현

2. 메인페이지 filtering 기능 구현
- 메인페이지에서 sorting 되고 있는 페이지에 옵션을 줘서 filtering 구현

3. 상세페이지 기능 구현
- product의 정보와 room의 정보 room_image의 정보를 다른 엔드포인트를 주어서 GET으로 요청시 반환할 수 있도록 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 쿼리문에서의 GROUP BY 에 대해서 좀 더 알게 되었고 반환해줘야 하는 정보를 최대한 작게 만들어서 주는 방법에 대해서 고민을 하고 쿼리문 작성을 통해 성장할 수 있는 시간을 가졌습니다.
- 막연히 어렵게 생각했던 다중필터에 대해서 지속적으로 고민하면서 많은 성장을 이룬 것 같습니다.
- 하나의 함수를 통해서만 정보를 뭉텅이로 주려고 했었는데 필요없는 정보를 제거하고 필요한 정보만 반환해야겠구나의 생각의 폭을 넓혔습니다.

<br />

## :: 기타 질문 및 특이 사항
- 메인페이지와 상세페이지 모두 달력과 관련된 로직을 만들어야 하는데 구현 중이여서 구현이 완료 되는 대로 다시 push할 예정입니다.

2022-11-07 12:47 UTC, sangwoong03 requested changes

2022-11-07 12:47 UTC, sangwoong03 commented on controllers/productController.js
> +    console.log(productId)
특정 로그 확인이 목적이 아닌`console.log()`는 삭제해주세요!

2022-11-07 12:47 UTC, sangwoong03 commented on routes/productRouter.js
> +router.get('/detail', productController.getProductInfoByProductId);
특정 `product`의 상세 정보를 처리하는 방법으로 `path parameters`를 사용할 수 있을 것 같네요!
나머지 부분도 path parameter를 사용하여 특정 데이터 정보에 접근할 수 있을 것 같습니다.

이에 따른 controller 단에서의 코드도 수정해주세요~!

```suggestion
router.get('/:productId', productController.getProductInfoByProductId);
```

2022-11-07 12:47 UTC, sangwoong03 commented on models/enums.js
> +});
가격 정보인가요 아니면 룸 타입인가요?

Enum type으로 지정한 RENTING_ROOM_ID와 LODGEMENT_ROOM_ID에 대한 값이 실제 문자열로 저장되는 데이터인가요??

2022-11-07 12:47 UTC, sangwoong03 commented on controllers/productController.js
> +    };
필터링은 특정 엔드포인트에서 특정 정보만을 골라 접근하고 싶을 때 query parameters를 사용하여 접근할 수 있습니다.

그렇기 때문에 개발을 할 때 전체 상품 리스트를 받아오는 엔드포인트를 작성하게 되고, query paramters는 부수적인 정보를 담고 있기 때문에 데이터 유무에 따른 예외처리를 할 필요가 없습니다.

만약 반드시 예외 처리가 필요하다면 에러 메시지를 `key error`로 통합하여 수정해주세요.
그렇지 않다면 로직에 대해 다시 한번 고민할 필요가 있어보입니다.

2022-11-07 12:47 UTC, sangwoong03 commented on models/productDao.js
> +        [offset, limit]
DAO에서 배열에 인자를 담아 매핑하는 부분도 있고, 아닌 부분도 있는 것 같습니다!
쿼리가 어떻게 동작하는지 확인 후 하나의 쿼리문 안에서는 동일한 매핑 방법을 사용할 수 있도록 수정해주세요!

2022-11-07 12:47 UTC, sangwoong03 commented on services/productService.js
> +    };
해당 코드는 실제 쿼리문에 대한 `switch-case` 구문으로 `productDao.getProductionInfo()` 함수 내부에서 사용되면 좋을 것 같습니다.

2022-11-07 12:47 UTC, sangwoong03 commented on services/productService.js
> +    console.log(optionArray);
불필요한 `console.log()` 는 push 하기 전 확인 후 삭제해주세요!

2022-11-07 12:47 UTC, sangwoong03 commented on services/productService.js
> +    };
이 부분은 내일 구두로 다시 여쭤볼게요!!

2022-11-07 12:48 UTC, sangwoong03 commented
해만님 package-lock.json 파일이 수정되어 올라와있는데 혹시 삭제하거나 추가한 모듈이 따로 있는 것인가요??

2022-11-08 04:35 UTC, haemong commented
제 파일에서 express가 제대로 작동하지 않아서 삭제하고 다시 깔았는데 그거 때문에 수정된 거 같습니다.

2022-11-08 04:45 UTC, haemong commented on models/enums.js
> +});
가격 정보입니다. 대실을 기본 가격에 4배 숙박을 12배로 하기 위해서 Enum type으로 상수를 저장했습니다.

2022-11-10 07:57 UTC, sangwoong03 requested changes
구두 수정 요청 사항 반영해주세요~!

2022-11-10 08:24 UTC, sangwoong03 approved these changes
고생하셨습니다 해만님 👍 
productService의 반복문 내부의 조건문 중첩에 대해서는 반드시 리팩토링을 시도해보는 것이 좋아보입니다~!

2022-11-10 08:24 UTC, merged